# Generated by Django 3.1.4 on 2020-12-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201215_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='social_ulr',
            field=models.URLField(blank=True, null=True),
        ),
    ]
