# Generated by Django 3.1.4 on 2020-12-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_student_social_ulr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='social_ulr',
            new_name='social_url',
        ),
    ]
