# Generated by Django 3.1.4 on 2020-12-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20201219_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='social_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
