# Generated by Django 2.2.6 on 2020-12-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20201228_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='normilized_name',
            new_name='normalized_name',
        ),
    ]
